### PR TITLE
fix(userspace/falco): when collecting metrics for stats_writer, create a `libs_metrics_collector` for each source

### LINKED ISSUE #3583: [Follow up fix] for `output_rule` and `output_file` metrics for multiple event sources scenarios
**Describe the bug**

Similar fix (see https://github.com/falcosecurity/falco/issues/3539, https://github.com/falcosecurity/falco/pull/3563) needed for `output_rule` and `output_file` for multiple event sources scenarios.

process_events.cpp snippet

```
// TODO: This may currently cause issues for multiple event sources. We are deferring
// the fix to Falco 0.42.0.
// For multiple event sources, it generates `n` metrics logs per source at a time, as
// expected, with the engine_name correctly reflected. However, the order may interfere,
// as the correct inspector for the syscalls event source seems to never get passed,
// resulting in most metrics being missing.
stats_collector.collect(inspector,
                        inspector->event_sources()[source_engine_idx],
                        num_evts);
```

**How to reproduce it**

Example output when running Falco <= 0.41.0 with just the syscalls event source

```
{"hostname":"test","output":"Falco metrics snapshot","output_fields":{"evt.hostname":"test","evt.source":"syscall","evt.time":1748454267833547951,"falco.container_memory_used_mb":0.0,"falco.cpu_usage_perc":15.0,"falco.duration_sec":0,"falco.host_boot_ts":1748282145000000000,"falco.host_cpu_usage_perc":6.6,"falco.host_memory_used_mb":9572.6,"falco.host_netinfo.interfaces.docker0.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.tun0.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.wlo1.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.wlo1.protocols.ipv6.addresses":"","falco.host_num_cpus":8,"falco.host_open_fds":18528,"falco.host_procs_running":2,"falco.kernel_release":"6.14.6-300.fc42.x86_64","falco.memory_pss_mb":53.5,"falco.memory_rss_mb":75.3,"falco.memory_vsz_mb":2446.3,"falco.n_added_fds":6813,"falco.n_added_threads":1718,"falco.n_cached_fd_lookups":0,"falco.n_cached_thread_lookups":0,"falco.n_drops_full_threadtable":0,"falco.n_failed_fd_lookups":0,"falco.n_failed_thread_lookups":0,"falco.n_fds":106671,"falco.n_noncached_fd_lookups":0,"falco.n_noncached_thread_lookups":8530,"falco.n_removed_fds":0,"falco.n_removed_threads":0,"falco.n_retrieve_evts_drops":0,"falco.n_retrieved_evts":0,"falco.n_store_evts_drops":0,"falco.n_stored_evts":0,"falco.n_threads":1718,"falco.num_evts":0,"falco.num_evts_prev":0,"falco.outputs_queue_num_drops":0,"falco.reload_ts":1748454267254235924,"falco.rules.Fileless_execution_via_memfd_create":0,"falco.rules.matches_total":0,"falco.sha256_config_file.falco_yaml":"4eddda74fc0171642ea2dd68b288eedaa45328a287313a270b0ed1a56ad4d583","falco.sha256_rules_file.falco_rules_test_yaml":"f04f92a4a03e65aae7765cb98ae7511a4a3be08d0d98d0be3f5bcb0607569cbb","falco.start_ts":1748454267252709881,"falco.version":"0.41.0-105+a7433e0","plugins.container.n_containers":16,"plugins.container.n_missing_container_images":0,"scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":0.0,"scap.n_drops":0,"scap.n_drops_buffer_clone_fork_enter":0,"scap.n_drops_buffer_clone_fork_exit":0,"scap.n_drops_buffer_close_exit":0,"scap.n_drops_buffer_connect_enter":0,"scap.n_drops_buffer_connect_exit":0,"scap.n_drops_buffer_dir_file_enter":0,"scap.n_drops_buffer_dir_file_exit":0,"scap.n_drops_buffer_execve_enter":0,"scap.n_drops_buffer_execve_exit":0,"scap.n_drops_buffer_open_enter":0,"scap.n_drops_buffer_open_exit":0,"scap.n_drops_buffer_other_interest_enter":0,"scap.n_drops_buffer_other_interest_exit":0,"scap.n_drops_buffer_proc_exit":0,"scap.n_drops_buffer_total":0,"scap.n_drops_bug":0,"scap.n_drops_page_faults":0,"scap.n_drops_perc":0.0,"scap.n_drops_prev":0,"scap.n_drops_scratch_map":0,"scap.n_evts":2,"scap.n_evts_prev":0},"priority":"Informational","rule":"Falco internal: metrics snapshot","source":"internal","time":"2025-05-28T17:44:27.833547951Z"}

```

Example outputs when running Falco <= 0.41.0 with (1) the syscalls event source and (2) the dummy_c event source

```

{"hostname":"test","output":"Falco metrics snapshot","output_fields":{"evt.hostname":"test","evt.source":"dummy_c","evt.time":1748454295419801795,"falco.container_memory_used_mb":0.0,"falco.cpu_usage_perc":11.0,"falco.duration_sec":0,"falco.host_boot_ts":1748282145000000000,"falco.host_cpu_usage_perc":6.6,"falco.host_memory_used_mb":9480.2,"falco.host_netinfo.interfaces.docker0.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.tun0.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.wlo1.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.wlo1.protocols.ipv6.addresses":"","falco.host_num_cpus":8,"falco.host_open_fds":18240,"falco.host_procs_running":3,"falco.kernel_release":"6.14.6-300.fc42.x86_64","falco.memory_pss_mb":22.6,"falco.memory_rss_mb":40.4,"falco.memory_vsz_mb":2006.9,"falco.num_evts":0,"falco.num_evts_prev":0,"falco.outputs_queue_num_drops":0,"falco.reload_ts":1748454295413215624,"falco.rules.Fileless_execution_via_memfd_create":0,"falco.rules.matches_total":0,"falco.sha256_config_file.falco_yaml":"411f941e13c56995e70dd5277f3875985f413368d78af8b4dbf3691087cc3685","falco.sha256_rules_file.falco_rules_test_yaml":"f04f92a4a03e65aae7765cb98ae7511a4a3be08d0d98d0be3f5bcb0607569cbb","falco.start_ts":1748454295413351849,"falco.version":"0.41.0-105+a7433e0","scap.engine_name":"source_plugin","scap.n_drops_perc":0.0},"priority":"Informational","rule":"Falco internal: metrics snapshot","source":"internal","time":"2025-05-28T17:44:55.419801795Z"}

{"hostname":"test","output":"Falco metrics snapshot","output_fields":{"evt.hostname":"test","evt.source":"syscall","evt.time":1748454295991578049,"falco.container_memory_used_mb":0.0,"falco.cpu_usage_perc":11.7,"falco.duration_sec":0,"falco.host_boot_ts":1748282145000000000,"falco.host_cpu_usage_perc":6.6,"falco.host_memory_used_mb":9578.3,"falco.host_netinfo.interfaces.docker0.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.tun0.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.wlo1.protocols.ipv4.addresses":"","falco.host_netinfo.interfaces.wlo1.protocols.ipv6.addresses":"","falco.host_num_cpus":8,"falco.host_open_fds":18496,"falco.host_procs_running":2,"falco.kernel_release":"6.14.6-300.fc42.x86_64","falco.memory_pss_mb":54.3,"falco.memory_rss_mb":76.5,"falco.memory_vsz_mb":2719.2,"falco.num_evts":0,"falco.num_evts_prev":0,"falco.outputs_queue_num_drops":0,"falco.reload_ts":1748454295413215624,"falco.rules.Fileless_execution_via_memfd_create":0,"falco.rules.matches_total":0,"falco.sha256_config_file.falco_yaml":"411f941e13c56995e70dd5277f3875985f413368d78af8b4dbf3691087cc3685","falco.sha256_rules_file.falco_rules_test_yaml":"f04f92a4a03e65aae7765cb98ae7511a4a3be08d0d98d0be3f5bcb0607569cbb","falco.start_ts":1748454295413351849,"falco.version":"0.41.0-105+a7433e0","scap.engine_name":"bpf","scap.n_drops_perc":0.0},"priority":"Informational","rule":"Falco internal: metrics snapshot","source":"internal","time":"2025-05-28T17:44:55.991578049Z"}

```

**Expected behavior**

Metric logs for the syscalls event source are equivalent when running Falco with or without an additional event source.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

In case multiple sources are enabled, each source has its own `libs_metrics_collector` with correct flags, so that it can retrieve all metrics.

**Which issue(s) this PR fixes**:

Fixes #3583

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(userspace/falco): when collecting metrics for stats_writer, create a `libs_metrics_collector` for each source
```

### CODE REVIEW

**Comment by FedeDP** [comment]
See the new output for stats writer, that is now as expected:
```
{"hostname":"federico.dipierro","output":"Falco metrics snapshot","output_fields":{"evt.hostname":"federico.dipierro","evt.source":"dummy","evt.time":1748503099414410497,"falco.container_memory_used_mb":0.0,"falco.cpu_usage_perc":114.3,"falco.duration_sec":0,"falco.host_boot_ts":1748435012000000000,"falco.host_cpu_usage_perc":4.5,"falco.host_memory_used_mb":12537.1,"falco.host_netinfo.interfaces.br-4882384366ef.protocols.ipv4.addresses":"172.18.0.1","falco.host_netinfo.interfaces.docker0.protocols.ipv4.addresses":"172.17.0.1","falco.host_netinfo.interfaces.lxcbr0.protocols.ipv4.addresses":"10.0.3.1","falco.host_netinfo.interfaces.virbr0.protocols.ipv4.addresses":"192.168.122.1","falco.host_netinfo.interfaces.wlp0s20f3.protocols.ipv4.addresses":"192.168.1.110","falco.host_netinfo.interfaces.wlp0s20f3.protocols.ipv6.addresses":"fe80:0:0:0:a1d7:584c:5842:375","falco.host_num_cpus":20,"falco.host_open_fds":20072,"falco.host_procs_running":3,"falco.kernel_release":"6.8.0-60-generic","falco.memory_pss_mb":72.7,"falco.memory_rss_mb":81.7,"falco.memory_vsz_mb":4288.6,"falco.num_evts":0,"falco.num_evts_prev":0,"falco.outputs_queue_num_drops":0,"falco.reload_ts":1748503099373483748,"falco.rules.Clear_Log_Activities":0,"falco.rules.Contact_K8S_API_Server_From_Container":0,"falco.rules.Create_Hardlink_Over_Sensitive_Files":0,"falco.rules.Create_Symlink_Over_Sensitive_Files":0,"falco.rules.Debugfs_Launched_in_Privileged_Container":0,"falco.rules.Detect_release_agent_File_Container_Escapes":0,"falco.rules.Directory_traversal_monitored_file_read":0,"falco.rules.Disallowed_SSH_Connection_Non_Standard_Port":0,"falco.rules.Drop_and_execute_new_binary_in_container":0,"falco.rules.Execution_from_dev_shm":0,"falco.rules.Fileless_execution_via_memfd_create":0,"falco.rules.Find_AWS_Credentials":0,"falco.rules.Linux_Kernel_Module_Injection_Detected":0,"falco.rules.Netcat_Remote_Code_Execution_in_Container":0,"falco.rules.PTRACE_anti_debug_attempt":0,"falco.rules.PTRACE_attached_to_process":0,"falco.rules.Packet_socket_created_in_container":0,"falco.rules.Read_sensitive_file_trusted_after_startup":0,"falco.rules.Read_sensitive_file_untrusted":0,"falco.rules.Redirect_STDOUT_STDIN_to_Network_Connection_in_Container":0,"falco.rules.Remove_Bulk_Data_from_Disk":0,"falco.rules.Run_shell_untrusted":0,"falco.rules.Search_Private_Keys_or_Passwords":0,"falco.rules.System_user_interactive":0,"falco.rules.Terminal_shell_in_container":0,"falco.rules.matches_total":0,"falco.sha256_config_file.falco_yaml":"f4c2b4174d2363a73743fec6a6f0649ace4e44d779941d7a277f502548735e0b","falco.sha256_rules_file.falco_rules_yaml":"6f0078862a26528cb50a860f9ebebbfbe3162e5009187089c73cb0cdf91d0b06","falco.start_ts":1748503099372600943,"falco.version":"0.41.0-105+a7433e0","scap.engine_name":"source_plugin","scap.n_drops_perc":0.0},"priority":"Informational","rule":"Falco internal: metrics snapshot","source":"internal","time":"2025-05-29T07:18:19.414410497Z"}

{"hostname":"federico.dipierro","output":"Falco metrics snapshot","output_fields":{"evt.hostname":"federico.dipierro","evt.source":"syscall","evt.time":1748503100374382835,"falco.container_memory_used_mb":0.0,"falco.cpu_usage_perc":94.2,"falco.duration_sec":1,"falco.host_boot_ts":1748435012000000000,"falco.host_cpu_usage_perc":4.5,"falco.host_memory_used_mb":12778.0,"falco.host_netinfo.interfaces.br-4882384366ef.protocols.ipv4.addresses":"172.18.0.1","falco.host_netinfo.interfaces.docker0.protocols.ipv4.addresses":"172.17.0.1","falco.host_netinfo.interfaces.lxcbr0.protocols.ipv4.addresses":"10.0.3.1","falco.host_netinfo.interfaces.virbr0.protocols.ipv4.addresses":"192.168.122.1","falco.host_netinfo.interfaces.wlp0s20f3.protocols.ipv4.addresses":"192.168.1.110","falco.host_netinfo.interfaces.wlp0s20f3.protocols.ipv6.addresses":"fe80:0:0:0:a1d7:584c:5842:375","falco.host_num_cpus":20,"falco.host_open_fds":20392,"falco.host_procs_running":1,"falco.kernel_release":"6.8.0-60-generic","falco.memory_pss_mb":99.7,"falco.memory_rss_mb":109.6,"falco.memory_vsz_mb":4765.8,"falco.n_added_fds":5928,"falco.n_added_threads":2226,"falco.n_cached_fd_lookups":0,"falco.n_cached_thread_lookups":0,"falco.n_drops_full_threadtable":0,"falco.n_failed_fd_lookups":0,"falco.n_failed_thread_lookups":0,"falco.n_fds":209016,"falco.n_noncached_fd_lookups":0,"falco.n_noncached_thread_lookups":8153,"falco.n_removed_fds":0,"falco.n_removed_threads":0,"falco.n_retrieve_evts_drops":0,"falco.n_retrieved_evts":0,"falco.n_store_evts_drops":0,"falco.n_stored_evts":0,"falco.n_threads":2226,"falco.num_evts":0,"falco.num_evts_prev":0,"falco.outputs_queue_num_drops":0,"falco.reload_ts":1748503099373483748,"falco.rules.Clear_Log_Activities":0,"falco.rules.Contact_K8S_API_Server_From_Container":0,"falco.rules.Create_Hardlink_Over_Sensitive_Files":0,"falco.rules.Create_Symlink_Over_Sensitive_Files":0,"falco.rules.Debugfs_Launched_in_Privileged_Container":0,"falco.rules.Detect_release_agent_File_Container_Escapes":0,"falco.rules.Directory_traversal_monitored_file_read":0,"falco.rules.Disallowed_SSH_Connection_Non_Standard_Port":0,"falco.rules.Drop_and_execute_new_binary_in_container":0,"falco.rules.Execution_from_dev_shm":0,"falco.rules.Fileless_execution_via_memfd_create":0,"falco.rules.Find_AWS_Credentials":0,"falco.rules.Linux_Kernel_Module_Injection_Detected":0,"falco.rules.Netcat_Remote_Code_Execution_in_Container":0,"falco.rules.PTRACE_anti_debug_attempt":0,"falco.rules.PTRACE_attached_to_process":0,"falco.rules.Packet_socket_created_in_container":0,"falco.rules.Read_sensitive_file_trusted_after_startup":0,"falco.rules.Read_sensitive_file_untrusted":0,"falco.rules.Redirect_STDOUT_STDIN_to_Network_Connection_in_Container":0,"falco.rules.Remove_Bulk_Data_from_Disk":0,"falco.rules.Run_shell_untrusted":0,"falco.rules.Search_Private_Keys_or_Passwords":0,"falco.rules.System_user_interactive":0,"falco.rules.Terminal_shell_in_container":0,"falco.rules.matches_total":0,"falco.sha256_config_file.falco_yaml":"f4c2b4174d2363a73743fec6a6f0649ace4e44d779941d7a277f502548735e0b","falco.sha256_rules_file.falco_rules_yaml":"6f0078862a26528cb50a860f9ebebbfbe3162e5009187089c73cb0cdf91d0b06","falco.start_ts":1748503099372600943,"falco.version":"0.41.0-105+a7433e0","plugins.container.n_containers":5,"plugins.container.n_missing_container_images":0,"scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":0.0,"scap.n_drops":0,"scap.n_drops_buffer_clone_fork_enter":0,"scap.n_drops_buffer_clone_fork_exit":0,"scap.n_drops_buffer_close_exit":0,"scap.n_drops_buffer_connect_enter":0,"scap.n_drops_buffer_connect_exit":0,"scap.n_drops_buffer_dir_file_enter":0,"scap.n_drops_buffer_dir_file_exit":0,"scap.n_drops_buffer_execve_enter":0,"scap.n_drops_buffer_execve_exit":0,"scap.n_drops_buffer_open_enter":0,"scap.n_drops_buffer_open_exit":0,"scap.n_drops_buffer_other_interest_enter":0,"scap.n_drops_buffer_other_interest_exit":0,"scap.n_drops_buffer_proc_exit":0,"scap.n_drops_buffer_total":0,"scap.n_drops_bug":0,"scap.n_drops_cpu_0":0,"scap.n_drops_cpu_1":0,"scap.n_drops_cpu_10":0,"scap.n_drops_cpu_11":0,"scap.n_drops_cpu_12":0,"scap.n_drops_cpu_13":0,"scap.n_drops_cpu_14":0,"scap.n_drops_cpu_15":0,"scap.n_drops_cpu_16":0,"scap.n_drops_cpu_17":0,"scap.n_drops_cpu_18":0,"scap.n_drops_cpu_19":0,"scap.n_drops_cpu_2":0,"scap.n_drops_cpu_3":0,"scap.n_drops_cpu_4":0,"scap.n_drops_cpu_5":0,"scap.n_drops_cpu_6":0,"scap.n_drops_cpu_7":0,"scap.n_drops_cpu_8":0,"scap.n_drops_cpu_9":0,"scap.n_drops_page_faults":0,"scap.n_drops_perc":0.0,"scap.n_drops_prev":0,"scap.n_drops_scratch_map":0,"scap.n_evts":2,"scap.n_evts_cpu_0":0,"scap.n_evts_cpu_1":0,"scap.n_evts_cpu_10":0,"scap.n_evts_cpu_11":0,"scap.n_evts_cpu_12":0,"scap.n_evts_cpu_13":0,"scap.n_evts_cpu_14":2,"scap.n_evts_cpu_15":0,"scap.n_evts_cpu_16":0,"scap.n_evts_cpu_17":0,"scap.n_evts_cpu_18":0,"scap.n_evts_cpu_19":0,"scap.n_evts_cpu_2":0,"scap.n_evts_cpu_3":0,"scap.n_evts_cpu_4":0,"scap.n_evts_cpu_5":0,"scap.n_evts_cpu_6":0,"scap.n_evts_cpu_7":0,"scap.n_evts_cpu_8":0,"scap.n_evts_cpu_9":0,"scap.n_evts_prev":0},"priority":"Informational","rule":"Falco internal: metrics snapshot","source":"internal","time":"2025-05-29T07:18:20.374382835Z"}
```

File: userspace/falco/stats_writer.cpp [hunk 1]
```diff
@@ -625,7 +629,7 @@ void stats_writer::collector::collect(const std::shared_ptr<sinsp>& inspector,
 				flags &= ~(METRICS_V2_KERNEL_COUNTERS | METRICS_V2_KERNEL_COUNTERS_PER_CPU |
 				           METRICS_V2_STATE_COUNTERS | METRICS_V2_LIBBPF_STATS);
 			}
-			m_writer->m_libs_metrics_collector =
+			m_writer->m_libs_metrics_collectors[src] =
```
Comment (FedeDP) [inline userspace/falco/stats_writer.cpp:632]: We cache it per-source.
In case of capture mode (ie: when we are reading a scap file), we will have multiple libs_metrics_collectors, one for each source, even if the inspector always stays the same (since all sources get attached to a single inspector in capture mode).

**Review by incertum — APPROVED** [review]
/hold

@FedeDP nice! Would you mind posting the fixed outputs logs either here or in the ticket as well as example similar to how you did it in the other PR? 

/approve

**Review by sgaist — APPROVED** [review]
