### PR TITLE
fix(userspace/engine): free formatters, if any

### LINKED ISSUE #1446: segmentation fault after SIGHUP
**Describe the bug**

Falco can restart itself when a SIGHUP is received (this feature was introduced by #457).

Unfortunately, with the current development version (ie. the current code on the master branch) when a SIGHUP is received then after a while Falco crashes (just before printing out any other alerts).

Note that this problem is not present in the last published version `0.26.1`.

**How to reproduce it**

Build Falco from sources. I used `cmake -DCMAKE_BUILD_TYPE=Release ..`.

Run Falco (eg. `sudo userspace/falco/falco -c /etc/falco/falco.yaml`) and generate some activity (eg. `sudo cat /etc/shadow`).

Send a SIGHUP (eg. `sudo kill -s SIGHUP <pid>`). 

Falco will restart itself as expected, then generate some activity (eg. `sudo cat /etc/shadow`) again, and Falco will crash.

**Expected behaviour**

No segmentation fault.

**Screenshots**

```
Thu Oct 15 18:37:43 2020: Falco version 0.26.1-43+47fa7d5 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
Thu Oct 15 18:37:43 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Thu Oct 15 18:37:43 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Thu Oct 15 18:37:43 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu Oct 15 18:37:43 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Thu Oct 15 18:37:44 2020: Starting internal webserver, listening on port 8765
18:37:48.016285983: Warning Sensitive file opened for reading by non-trusted program (user=root user_loginuid=1000 program=cat command=cat /etc/shadow file=/etc/shadow parent=sudo gparent=zsh ggparent=tmux: gggparent=systemd container_id=host image=<NA>)
Thu Oct 15 18:38:08 2020: SIGHUP received, restarting...
Events detected: 1
Rule counts by severity:
   WARNING: 1
Triggered rules by rule name:
   Read sensitive file untrusted: 1
Syscall event drop monitoring:
   - event drop detected: 0 occurrences
   - num times actions taken: 0
Thu Oct 15 18:38:08 2020: Falco version 0.26.1-43+47fa7d5 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
Thu Oct 15 18:38:08 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Thu Oct 15 18:38:08 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Thu Oct 15 18:38:08 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu Oct 15 18:38:08 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Thu Oct 15 18:38:09 2020: Starting internal webserver, listening on port 8765
[1]    180475 segmentation fault  sudo userspace/falco/falco -c /etc/falco/falco.yaml
```

**Environment**

- Falco version: ` 0.26.1-43+47fa7d5 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)`

- System info:

- Cloud provider or hardware configuration:
- OS: Arch
- Kernel: `5.8.14-arch1-1`

- Installation method: from source

**Additional context**

This problem might be related to https://github.com/falcosecurity/falco/pull/1412

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

Previously, formatters were freed by LUA code when re-opening outputs.
Since now, outputs are not controlling anymore the falco_formats class (see #1412), we just free formatters only if were already initialized.

That is needed when the engine restarts (see #1446).

By doing so, we also ensure that the correct inspector instance is set to the formatter cache.

**Which issue(s) this PR fixes**:

Fixes #1446

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: userspace/engine/formats.cpp [hunk 1]
```diff
@@ -44,8 +44,10 @@ void falco_formats::init(sinsp *inspector,
 	s_json_include_output_property = json_include_output_property;
 	if(!s_formatters)
 	{
-		s_formatters = new sinsp_evt_formatter_cache(s_inspector);
+		delete(s_formatters);
+		s_formatters = NULL;
```
Comment (leodido) [inline userspace/engine/formats.cpp:48]: Why assigning it to `NULL` after the `delete`?

There's the possibility of a double delete?

Also, maybe it's the case to think about a "smart" pointer here. Even to reason if we now need a pointer or not here...

**Review by leodido — COMMENTED** [review]
Please take a look at my comment :)

File: userspace/engine/formats.cpp (hunk 1 above)
Comment (leogr) [reply userspace/engine/formats.cpp:48]: It's a WIP, and I was just trying the previous approach:
https://github.com/falcosecurity/falco/blob/0a449afc3ed0efc7d6ddf66fe206d4081ee405ae/userspace/engine/formats.cpp#L115-L123

Comment (leogr) [reply userspace/engine/formats.cpp:48]: And ofc, now there's no need to assign it to `NULL` since two lines below it gets assigned to `new sinsp_evt_formatter_cache(s_inspector)` always (so no way to double delete it):

https://github.com/falcosecurity/falco/blob/c0f3b5acf4b53970549569e8feadbe5710c4d88c/userspace/engine/formats.cpp#L50

Alternatively, an `std::unique_ptr` should work here too.

However, you're probably right: we don't really need a pointer here. I will try that.

Thanks for the hints!

Comment (leogr) [reply userspace/engine/formats.cpp]: Fixed.

N.B.
Although the pointer is not really needed, removing it implies having an empty `sinsp_evt_formatter_cache` for a while (when declaring the static member) and later freed at the first `init` call. That can lead to problems if `sinsp_evt_formatter_cache` implementation changed in the future. Thus I opted to keep the pointer (with `std::unique_ptr`).

**Comment by leogr** [comment]
Ready for review.

Thanks, @leodido for the suggestions.

**Review by fntlnz — APPROVED** [review]

**Comment by fntlnz** [comment]
We can probably use `make_shared` from cpp+20 here/ I know that we are on C++11 so we might just use the polyfills from abseil cpp that we already have for gRPC .

abseil: https://github.com/abseil/abseil-cpp
grpc importing abseil: https://github.com/falcosecurity/falco/blob/master/cmake/modules/gRPC.cmake#L119

**Comment by fntlnz** [comment]
Putting an hold since this is blocking the merge queue. Feel free to remove once it's approved by two maintainers.

/hold

**Review by leodido — APPROVED** [review]

**Comment by leogr** [comment]
/hold cancel

:partying_face:
