### PR TITLE
fix: set http output contenttype to text/plain when json output is disabled

### LINKED ISSUE #1824: `http_output` always uses "Content-Type: application/json" even if json formatting is disabled
**Describe the bug**

`Content-Type: application/json` is always sent :point_down: 

https://github.com/falcosecurity/falco/blob/f035829ca2881b70a4d13e22abb5f8eb828d3a5f/userspace/falco/outputs_http.cpp#L31

regardless of the value of json formatting option :point_down: 

https://github.com/falcosecurity/falco/blob/f035829ca2881b70a4d13e22abb5f8eb828d3a5f/falco.yaml#L68

**How to reproduce it**

**Expected behaviour**

Perhaps, `text/plain` when `json_output: false` ?

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:
The PR sets the http output Content-type header to a more meaningful value (text/plain) when json_output is disabled.

**Which issue(s) this PR fixes**:

Fixes #1824 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: set http output contenttype to text/plain when json output is disabled
```

### CODE REVIEW

File: userspace/falco/outputs.h [hunk 1]
```diff
@@ -51,6 +51,7 @@ struct message
 	std::string source;
 	map<std::string, std::string> fields;
 	std::set<std::string> tags;
+	gen_event_formatter::output_format format;
```
Comment (leogr) [inline userspace/falco/outputs.h:54]: Could we avoid passing the formatter in the message?

This approach cannot work with `internal` messages, that do not have a formatter :point_down: 
https://github.com/falcosecurity/falco/blob/226d1fb7284319b5dfb7cbed50281ca11cfda7ad/userspace/falco/falco_outputs.cpp#L199-L213

Moreover, the JSON formatting option is a global setting (not a per-message setting) and the message already contains the formatted text. So I believe the formatter does not really belong to the message.

I would rather pass the `m_json_output`'s value to each output via the `init` function :point_down: 
https://github.com/falcosecurity/falco/blob/226d1fb7284319b5dfb7cbed50281ca11cfda7ad/userspace/falco/falco_outputs.cpp#L138

**Review by leogr — COMMENTED** [review]
Hey @FedeDP 

Thank you for this PR! We really need to fix that.
However, we shouldn't pass the formatter to the output channels. Moreover, if I understood correctly, your implementation won't work with internal messages (because they don't get a formatter). See my comment below.

I propose instead to propagate `m_json_ouput` to the output channels during init.

File: userspace/falco/outputs.h (hunk 1 above)
Comment (FedeDP) [reply userspace/falco/outputs.h:54]: Much simpler, you're right! Thanks ;)

**Review by leogr — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
Thanks @FedeDP! ❤️ 

/approve
