### PR TITLE
fix(userspace/falco): timer_delete() workaround due to bug in older GLIBC

### LINKED ISSUE #2850: Falco 0.36 and later segfaults on startup when metrics are enabled
**Describe the bug**

Falco fails to start with a segfault when the metrics option is enabled in the config. I tried disabling the sub-options and it doesn't make a difference.

**How to reproduce it**

- Install Falco 0.36.0 or later
- Enable metrics in the config and run Falco

Example output:
```
# falco --modern-bpf -o log_level=debug -o log_stderr=true -o libs_logger.enabled=true -o libs_logger.severity=debug
Tue Oct  3 14:32:28 2023: Falco version: 0.37.0-55+29d2406 (x86_64)
Tue Oct  3 14:32:28 2023: CLI args: falco --modern-bpf -o log_level=debug -o log_stderr=true -o libs_logger.enabled=true -o libs_logger.severity=debug
Tue Oct  3 14:32:28 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Tue Oct  3 14:32:28 2023: Configured rules filenames:
Tue Oct  3 14:32:28 2023:    /etc/falco/falco_rules.yaml
Tue Oct  3 14:32:28 2023:    /etc/falco/falco_rules.local.yaml
Tue Oct  3 14:32:28 2023:    /etc/falco/rules.d
Tue Oct  3 14:32:28 2023: Loading rules from file /etc/falco/falco_rules.yaml
Tue Oct  3 14:32:28 2023: Loading rules from file /etc/falco/falco_rules.local.yaml
Tue Oct  3 14:32:28 2023: Watching file '/etc/falco/falco.yaml'
Tue Oct  3 14:32:28 2023: Watching file '/etc/falco/falco_rules.yaml'
Tue Oct  3 14:32:28 2023: Watching file '/etc/falco/falco_rules.local.yaml'
Tue Oct  3 14:32:28 2023: Watching directory '/etc/falco/rules.d'
Tue Oct  3 14:32:28 2023: Setting metadata download max size to 100 MB
Tue Oct  3 14:32:28 2023: Setting metadata download chunk wait time to 1000 μs
Tue Oct  3 14:32:28 2023: Setting metadata download watch frequency to 1 seconds
Tue Oct  3 14:32:28 2023: (19) syscalls in rules: connect, dup, dup2, dup3, execve, execveat, finit_module, init_module, link, linkat, open, openat, openat2, ptrace, sendmsg, sendto, socket, symlink, symlinkat
Tue Oct  3 14:32:28 2023: +(49) syscalls (Falco's state engine set of syscalls): accept, accept4, bind, capset, chdir, chroot, clone, clone3, close, creat, epoll_create, epoll_create1, eventfd, eventfd2, fchdir, fcntl, fork, getsockopt, inotify_init, inotify_init1, io_uring_setup, memfd_create, mount, open_by_handle_at, pidfd_getfd, pidfd_open, pipe, pipe2, prctl, prlimit, procexit, recvfrom, recvmsg, setgid, setpgid, setresgid, setresuid, setrlimit, setsid, setuid, shutdown, signalfd, signalfd4, socketpair, timerfd_create, umount, umount2, userfaultfd, vfork
Tue Oct  3 14:32:28 2023: (68) syscalls selected in total (final set): accept, accept4, bind, capset, chdir, chroot, clone, clone3, close, connect, creat, dup, dup2, dup3, epoll_create, epoll_create1, eventfd, eventfd2, execve, execveat, fchdir, fcntl, finit_module, fork, getsockopt, init_module, inotify_init, inotify_init1, io_uring_setup, link, linkat, memfd_create, mount, open, open_by_handle_at, openat, openat2, pidfd_getfd, pidfd_open, pipe, pipe2, prctl, prlimit, procexit, ptrace, recvfrom, recvmsg, sendmsg, sendto, setgid, setpgid, setresgid, setresuid, setrlimit, setsid, setuid, shutdown, signalfd, signalfd4, socket, socketpair, symlink, symlinkat, timerfd_create, umount, umount2, userfaultfd, vfork
Tue Oct  3 14:32:28 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Tue Oct  3 14:32:28 2023: Setting metrics interval to 1h, equivalent to 3600000 (ms)
Segmentation fault (core dumped)
```
**Expected behaviour**

Falco doesn't crash. This behavior began when upgrading from 0.35.1 to 0.36.0. This also occurs on the most recent dev build of 0.37.

**Environment**

- Falco version: 0.36.0 through 0.37.0-55+29d2406 (most recent dev build)

- System info: Architecture: x86_64

- Cloud provider or hardware configuration: AWS
- OS: CentOS Stream

- Kernel: 5.15.86

- Installation method: RPM

**Additional context**

Core dump stacktrace:
```
Message: Process 3088612 (falco) of user 0 dumped core.

                Stack trace of thread 3088612:
                #0  0x00007fb5e334f5c2 timer_delete@@GLIBC_2.3.3 (librt.so.1)
                #1  0x000000000057eff6 n/a (falco)
                #2  0x0000000000530f71 n/a (falco)
                #3  0x00000000004f1402 n/a (falco)
                #4  0x00000000004efe4a n/a (falco)
                #5  0x00000000004f1397 n/a (falco)
                #6  0x00000000004aa8a6 n/a (falco)
                #7  0x00007fb5e2289d85 __libc_start_main (libc.so.6)
                #8  0x00000000004bb555 n/a (falco)

                Stack trace of thread 3088616:
                #0  0x00007fb5e22889bd syscall (libc.so.6)
                #1  0x000000000106d395 n/a (falco)
                #2  0x00000000005778e4 n/a (falco)
                #3  0x0000000000570eff n/a (falco)
                #4  0x00000000012c8910 n/a (falco)
                #5  0x00007fb5e355b1ca start_thread (libpthread.so.0)
                #6  0x00007fb5e2288e73 __clone (libc.so.6)

                Stack trace of thread 3088617:
                #0  0x00007fb5e3565180 __nanosleep (libpthread.so.0)
                #1  0x0000000000575cc3 n/a (falco)
                #2  0x00000000012c8910 n/a (falco)
                #3  0x00007fb5e355b1ca start_thread (libpthread.so.0)
                #4  0x00007fb5e2288e73 __clone (libc.so.6)

                Stack trace of thread 3088618:
                #0  0x00007fb5e237567f __select (libc.so.6)
                #1  0x00000000005cf956 n/a (falco)
                #2  0x00000000012c8910 n/a (falco)
                #3  0x00007fb5e355b1ca start_thread (libpthread.so.0)
                #4  0x00007fb5e2288e73 __clone (libc.so.6)

                Stack trace of thread 3088619:
                #0  0x00007fb5e22889bd syscall (libc.so.6)
                #1  0x000000000106d395 n/a (falco)
                #2  0x0000000000584ad7 n/a (falco)
                #3  0x00000000012c8910 n/a (falco)
                #4  0x00007fb5e355b1ca start_thread (libpthread.so.0)
                #5  0x00007fb5e2288e73 __clone (libc.so.6)
```
Please let me know if you need anymore information.

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

Workaround for older GLIBC versions (< 2.35), where calling timer_delete() with an invalid timer ID not returned by timer_create() causes a segfault because of a bug in GLIBC (https://sourceware.org/bugzilla/show_bug.cgi?id=28257).

See also https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1940296.

Also verified it on:

```
[vagrant@centos7 ~]$ uname -r
5.14.15-1.el7.elrepo.x86_64
ldd --version
ldd (GNU libc) 2.17
[vagrant@amazonlinux2 ~]$ uname -r
4.14.314-237.533.amzn2.x86_64
ldd --version
ldd (GNU libc) 2.26
```

and discovered it via backtracing using gdb debugger.

Impact: High for adopters using the metrics feature on a system with impacted GLIBC version.

@FedeDP @Andreagit97 @jasondellaluce curious, would you have a better workaround idea? Also couldn't come up with a good unit testing idea other than adding a test to the falco testing repo https://github.com/falcosecurity/testing/pull/30.

**Which issue(s) this PR fixes**:

Fixes #2850

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(userspace/falco): timer_delete() workaround due to bug in older GLIBC
```

### CODE REVIEW

**Comment by incertum** [comment]
Can address the codespell issues at the end.

**Comment by FedeDP** [comment]
Hey melissa, incidentally i just fixed that yesterday: https://github.com/falcosecurity/falco/issues/2850
Do you like my approach?

**Comment by FedeDP** [comment]
I was going to push the branch and open the PR today :D

**Review by FedeDP — APPROVED** [review]
/approve

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

File: userspace/falco/stats_writer.cpp [hunk 1]
```diff
@@ -134,7 +153,10 @@ stats_writer::~stats_writer()
 		}
 		// delete timerID and reset timer
 #ifndef __EMSCRIPTEN__
-		timer_delete(s_timerid);
+		if (s_timerid_exists)
+		{
+			timer_delete(s_timerid);
```
Comment (Andreagit97) [inline userspace/falco/stats_writer.cpp:158]: i would add `s_timerid_exists = false;` after the delete

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve
