### PR TITLE
fix: do the inspector after forking for daemon mode

### LINKED ISSUE #716: Falco is not showing container information. All container events are coming with name "incomplete"
**What happened**:

Falco is not showing container related information. All container events are coming with name "incomplete".

**What you expected to happen**:

Container events should come with the container information. I know that few events would come without container names due to the new design, however, even when container is running for more than an hour, still  information is not present.

**How to reproduce it (as minimally and precisely as possible)**:

In an already running container, we created a shell and then ran the command "nc". It reported the alert with the container name "incomplete". We are seeing other events as well coming out with container information.

**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`): 0.15.3
- System info 
- Cloud provider or hardware configuration: AWS/Docker/ECS
- OS (e.g: `cat /etc/os-release`):Amazon Linux 2
- Kernel (e.g. `uname -a`):4.14.123-111.109.amzn2.x86_64 
- Install tools (e.g. in kubernetes, rpm, deb, from source):rpm
- Others:

### PR DESCRIPTION
**Pull request by fntlnz**
**What type of PR is this?**
/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

When falco is started in daemon node, it does not carry the threads related to container metadata and in general all the other threads done before the fork because `fork` only carries the main thread.

This solves that problem by moving all the thread openings after fork.

**Which issue(s) this PR fixes**:

Fixes #716

**Special notes for your reviewer**:

Here are packages to test:
DEB
Download: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz-test-x86_64.deb
Sha256: 1586eea70cd750f730341a0dfa83275d7893fa5aca0c0f0929d0b3df5557c000  falco-fntlnz-test-x86_64.deb

RPM
Download: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz-test-x86_64.rpm
Sha256: 60c8eda61db76d50e78403c73304c2d77dff6fe62901852bf995222b81e81abc  falco-fntlnz-test-x86_64.rpm

TAR.GZ
Download: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz-test-x86_64.tar.gz
Sha256: 4b6917d1369b55d757e9eaa6c4e0b9b7e915c279611850c6c6e63a2a4cd095a8  falco-fntlnz-test-x86_64.tar.gz
**Does this PR introduce a user-facing change?**:

```release-note
fix: container metadata are now fetched when the falco process is run in daemon mode
```

### CODE REVIEW

File: userspace/falco/falco.cpp [hunk 1]
```diff
@@ -915,64 +915,6 @@ int falco_init(int argc, char **argv)
...
-			{
-				if(system("modprobe " PROBE_NAME " > /dev/null 2> /dev/null"))
-				{
-					falco_logger::log(LOG_ERR, "Unable to load the driver. Exiting.\n");
-				}
-				inspector->open();
-			}
-		}
-
 		// This must be done after the open
```
Comment (mfdii) [inline userspace/falco/falco.cpp]: this needs to move after the open

**Comment by mfdii** [comment]
confirmed this works, however the `inspector->start_dropping_mode(1);` call needs to be moved to after the `innspector->open()`

**Comment by fntlnz** [comment]
Thanks @mfdii forgot that one! Updated PTAL

**Comment by fntlnz** [comment]
I compiled packages for those who want to test this on x86_64:


DEB: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz-test-x86_64.deb
RPM: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz-test-x86_64.rpm
TAR.GZ: https://falco-dev-public.s3.amazonaws.com/pr-731/falco-fntlnz-test-x86_64.tar.gz

**Comment by leodido** [comment]
Pls rebase and I'll merge this! Thanks @fntlnz :)
