### PR TITLE
fix(engine): show condition text in warning snippet for folded scalar conditions

### LINKED ISSUE #3857: Default rules using YAML folded scalar > causes LOAD_DEPRECATED_ITEM false warning about evt.dir
When Falco loads default rules that use the YAML folded scalar > for multi-line values (condition: >), the parser appears to misinterpret the > character, producing incorrect deprecation warnings referencing evt.dir, example:

```
In rules content: (/etc/falco/falco_rules.yaml:0:0)
    rule 'Fileless execution via memfd_create': (/etc/falco/falco_rules.yaml:1243:2)
    rule condition: (/etc/falco/falco_rules.yaml:1249:13)
------
  condition: >
             ^
------
LOAD_DEPRECATED_ITEM (Used deprecated item: field 'evt.dir'): due to the drop of enter events, 'evt.dir = <' always evaluates to true, and 'evt.dir = >' always evaluates to false. The rule expression can be simplified by removing the condition on 'evt.dir'
```

The affected rules (e.g. Fileless execution via memfd_create) do not contain any reference to evt.dir. The warning points at the > character on the condition.

**Steps to reproduce:**
Deploy Falco via Helm with default rules
Check Falco logs for LOAD_DEPRECATED_ITEM warnings
Inspect the flagged rules — they contain no evt.dir usage

**Expected behavior:**
No warning should be emitted for rules that don't use evt.dir.

**Environment**
Falco version: 0.43.1 (x86_64)
Helm chart version: 8.0.2
Platform: GKE

### PR DESCRIPTION
**Pull request by ssam18**
When a rule condition uses YAML folded scalar syntax (`condition: >`), the warning snippet was pointing at the `>` character, making it look like the YAML indicator itself was causing the deprecated field warning (e.g. `evt.dir`). The fix wraps the warning context with the actual condition text, consistent with how compile errors are already handled in the same code path. Added a regression test covering this case. Fixes #3857 

/kind bug
/area engine

```release-note
fix: show condition text in warning snippet for folded scalar conditions
```

### CODE REVIEW

File: unit_tests/engine/test_rule_loader.cpp [hunk 1]
```diff
@@ -1516,3 +1516,28 @@ TEST_F(test_falco_engine, no_deprecated_field_warning_in_output) {
 	ASSERT_FALSE(check_warning_message("evt.dir")) << m_load_result_string;
 	EXPECT_EQ(num_rules_for_ruleset(), 1);
 }
+
+TEST_F(test_falco_engine, deprecated_evt_dir_folded_scalar_condition_snippet) {
```
Comment (leogr) [inline unit_tests/engine/test_rule_loader.cpp:1520]: Non-blocking: #3857 describes the warning firing on a rule whose *macros* reference `evt.dir` indirectly (not the rule condition itself). May you add a second test case where `evt.dir` is hidden inside a macro the rule depends on? It would mirror the bug report more closely and guard against divergence if the warning emission path ever gains per-node positions. Not a blocker for this PR 🙏

**Review by leogr — COMMENTED** [review]
Hey @ssam18, welcome and thanks for the fix 🙏

Nice work. The approach is consistent with how compile errors and compile warnings are already wrapped a few lines below in the same function (see `rule_loader_compiler.cpp:387` and `:398`), which is exactly the right pattern to reuse here. The regression test covers the folded-scalar case well. Left one small non-blocking note inline.

I found just nit (see my comment below). Let me know if you want to fix it in this PR.

**Comment by leogr** [comment]
Also, a friendly reminder for the future: DO NOT remove the PR template, please. We put it there for a reason :sweat_smile: 

I will fix it for this time, so no action is needed from you.

**Comment by leogr** [comment]
> This PR may bring feature or behavior changes in the Falco engine and may require the engine version to be bumped.
> 
> Please double check **userspace/engine/falco_engine_version.h** file. See [versioning for FALCO_ENGINE_VERSION](https://github.com/falcosecurity/falco/blob/master/RELEASE.md#falco-repo-this-repo).
> 
> /hold

false positive

/hold cancel

**Review by leogr — APPROVED** [review]
Thanks for the follow-up 🙏

LGTM now.

**Comment by leogr** [comment]
cc @falcosecurity/falco-maintainers

**Review by sgaist — APPROVED** [review]
