### PR TITLE
fix(userspace/falco): fix outputs_http timeout

### LINKED ISSUE #3522: alert lost with http_output because of libcurl timeout
**Describe the bug**

when network is lost, alert is lost after libcurl timeout

**How to reproduce it**

* set a http_output to a falcosidekick:

```yaml
json_output: true
json_include_output_property: true
http_output:
  enabled: true
  keep_alive: true
  url: "http://YOURHOST:2801/"
```

* disable the network (in my case, i just block port with iptables)

```bash
iptables -A OUTPUT -p tcp --dport 2801 -j DROP
```

* launch falco with default rules (in my case in modern ebpf mode)

```bash
falco -o engine.kind=modern_ebpf
```

* do a violation

```bash
cat /etc/shadow
```

*  see falco logs

```bash
# falco logs
{"hostname":"test1","output":"17:15:03.434319636: Warning Sensitive file opened for reading by non-trusted program (file=/etc/shadow gparent=sshd ggparent=sshd gggparent=sshd evt_type=openat user=root user_uid=0 user_loginuid=0 process=cat proc_exepath=/usr/bin/cat parent=bash command=cat /etc/shadow terminal=34817 container_id=host container_name=host) TEST 500","output_fields":{"container.id":"host","container.name":"host","evt.num":1915,"evt.time":1743606903434319636,"evt.type":"openat","fd.name":"/etc/shadow","proc.aname[2]":"sshd","proc.aname[3]":"sshd","proc.aname[4]":"sshd","proc.cmdline":"cat /etc/shadow","proc.exepath":"/usr/bin/cat","proc.name":"cat","proc.pname":"bash","proc.tty":34817,"user.loginuid":0,"user.name":"root","user.uid":0},"priority":"Warning","rule":"Read sensitive file untrusted","source":"syscall","tags":["T1555","container","filesystem","host","maturity_stable","mitre_credential_access"],"time":"2025-04-02T15:15:03.434319636Z"}
Wed Apr  2 17:15:05 2025: "http" output timeout, all output channels are blocked

# after CURL_TIMEOUT (about 3 minutes)

Wed Apr  2 17:18:07 2025: libcurl failed to perform call: Timeout was reached

```

*Notes*

if i reactivate the network before CURL_TIMEOUT the alert is sent
and if i open other /etc/shadow files the other alerts will be sent

**Expected behaviour**

send the alert when the network is back (at least independently of the curl timeout error)

**Environment**

- Falco version:

Wed Apr  2 17:36:16 2025: Falco version: 0.0.0 (x86_64)
Wed Apr  2 17:36:16 2025: Falco initialized with configuration files:
Wed Apr  2 17:36:16 2025:    /etc/falco/config.d/engine-kind-falcoctl.yaml | schema validation: ok
Wed Apr  2 17:36:16 2025:    /etc/falco/falco.yaml | schema validation: failed for <root>: Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints: ''.
Wed Apr  2 17:36:16 2025: System info: Linux version 5.14.0-64.baseos.rpbatz.x86_64 (mockbuild@df273706113145ef9e8d3883fda7441d) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-37.baseos.rpbatz) #1 SMP Mon Sep 11 15:39:09 CEST 2023
{"default_driver_version":"7.3.0+driver","driver_api_version":"8.0.0","driver_schema_version":"2.0.0","engine_version":"43","engine_version_semver":"0.43.0","falco_version":"0.0.0","libs_version":"0.18.1","plugin_api_version":"3.7.0"}
- System info:

{
  "machine": "x86_64",
  "nodename": "test1",
  "release": "5.14.0-64.baseos.rpbatz.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Sep 11 15:39:09 CEST 2023"
}

- Cloud provider or hardware configuration:
- OS:

- Kernel:
Linux test1 5.14.0-64.baseos.rpbatz.x86_64 #1 SMP Mon Sep 11 15:39:09 CEST 2023 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
rpm custom

**Additional context**

### PR DESCRIPTION
**Pull request by benierc**
libcurl timeout prevent to send alert through http keep trying to send the alert

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

this PR  ignore http_output libcurl timeout when network is not available, 
it allows to send the alert when network is back and to not lost it

**Which issue(s) this PR fixes**:

Fixes #3522

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thanks for the PR! I left a comment to avoid the unbound loop ;)
/milestone 0.41.0

**Comment by FedeDP** [comment]
Hi @benierc ! Great job! You need to update config json schema too with the new config key: https://github.com/falcosecurity/falco/blob/master/userspace/falco/config_json_schema.h

File: userspace/falco/configuration.cpp [hunk 1]
```diff
@@ -447,6 +447,11 @@ void falco_configuration::load_yaml(const std::string &config_name) {
 		keep_alive = m_config.get_scalar<bool>("http_output.keep_alive", false);
 		http_output.options["keep_alive"] = keep_alive ? std::string("true") : std::string("false");
 
+		uint32_t max_consecutive_timeouts;
+		max_consecutive_timeouts =
+		        m_config.get_scalar<uint32_t>("http_output.max_consecutive_timeouts", 5);
```
Comment (sgaist) [inline userspace/falco/configuration.cpp:452]: Shouldn't `m_max_consecutive_timeouts` be enclosed in a range to avoid having an "almost" infinite loop if someone inputs a high value ?

Maybe also use a type smaller than unit32 to store it.

Comment (benierc) [reply userspace/falco/configuration.cpp:452]: ok i see, so an uint16_t or uint8_t should be better @sgaist ?

Comment (sgaist) [reply userspace/falco/configuration.cpp:452]: unit8's max being 255, I think it should already cover most use cases.

If there's a need in the future to have more than that number of retries, it's always possible to update at this time.

Comment (FedeDP) [reply userspace/falco/configuration.cpp]: uint8_t makes sense IMHO!

File: userspace/falco/config_json_schema.h [hunk 2]
```diff
@@ -514,6 +514,9 @@ const char config_schema_string[] = LONG_STRING_CONST(
                 },
                 "keep_alive": {
                     "type": "boolean"
+                },
+                "max_consecutive_timeouts:" {
```
Comment (FedeDP) [inline userspace/falco/config_json_schema.h:518]:
```suggestion
                "max_consecutive_timeouts": {
```
:P

Comment (FedeDP) [reply userspace/falco/config_json_schema.h:518]: This will fix the CI @benierc !

**Review by sgaist — CHANGES_REQUESTED** [review]
Sorry, I just saw that my review wasn't submitted !

We're on the right track :-)

File: userspace/falco/config_json_schema.h (hunk 2 above)
Comment (benierc) [reply userspace/falco/config_json_schema.h]: thx a lot!

File: userspace/falco/outputs_http.cpp [hunk 3]
```diff
@@ -36,6 +36,8 @@ bool falco::outputs::output_http::init(const config &oc,
 
 	m_curl = nullptr;
 	m_http_headers = nullptr;
+	m_max_consecutive_timeouts =
+	        static_cast<uint8_t>(std::stoi(m_oc.options["max_consecutive_timeouts"]));
```
[the remark this answers is not in the document]
Comment (benierc) [reply userspace/falco/outputs_http.cpp]: add it! thank you

**Comment by FedeDP** [comment]
The CI failures do not come from this PR! You will need to rebase once https://github.com/falcosecurity/falco/pull/3537 is merged :)

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
@sgaist PTAL :pray:

**Review by sgaist — APPROVED** [review]
LGTM
