### PR TITLE
fix(userspace/falco): fixed `falco_metrics::to_text` implementation when running with plugins

### LINKED ISSUE #3229: Scraping prometheus metrics endpoint crashes falco process
**Describe the bug**

Followed the prometheus support section in the docs to enable the /metrics endpoint. A soon as you make a request to this endpoint the falco process crashes without any indication on stdout/stderr what went wrong.

**How to reproduce it**

```
engine:
  kind: nodriver

metrics:
  enabled: true
  interval: 1h (also tried with 1m and waiting ~ 5 mins before /metrics request)
  output_rule: true
  rules_counters_enabled: false (tried with only this one enabled)
  resource_utilization_enabled: false (tried with only this one enabled)
  state_counters_enabled: false
  kernel_event_counters_enabled: false
  libbpf_stats_enabled: false
  convert_memory_to_mb: true
  include_empty_values: false

webserver:
  enabled: true
  k8s_healthz_endpoint: /healthz
  listen_port: 8765
  prometheus_metrics_enabled: true
```

Enabled debug logging as well:
```
libs_logger:
  enabled: true
  severity: debug
log_level: debug
```

This doesn't give any output when requesting the /metrics endpoint. So, it is not helping narrowing down what it happening just before it crashes.

This is what happens with a port forward to the falco pod:
```
% curl localhost:8765/healthz
{"status": "ok"}

% curl localhost:8765/metrics
curl: (52) Empty reply from server
```

After the `/metrics` request has been done, Kubernetes shows pod termination:
```
      lastState:
        terminated:
          exitCode: 139
          reason: Error
```

**Expected behaviour**

Expected to see some metrics, or at least not to crash the entire falco process.

**Screenshots**

**Environment**

- Falco version: 0.38.0 (x86_64)

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method: Kubernetes (docker.io/falcosecurity/falco-no-driver image)

**Additional context**

This is a dedicated github plugin instance of falco (running as a k8s pod), i.e. not using syscall at all (`--disable-source syscall`).

```
2024-05-31T09:43:33+0000: Loaded event sources: syscall, github
2024-05-31T09:43:33+0000: Enabled event sources: github
2024-05-31T09:43:33+0000: Opening event source 'github'
```

No clue if this has anything to do with the crash though.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

This PR does 3 things:
* avoid crashing when scap_machine_info or scap_agent_info are NULL (ie: with non-linux scap platform, ie: while running plugins)
* properly use a `shared_ptr` for inspectors vector, so that we know they are kept alive while `to_text` runs and we can dereference the pointer
* only expose metrics for actually enabled sources (not loaded ones). Before, in `nodriver` mode with syscall source disabled, we would've tried to emit metrics for the syscall source/inspector too, but that is wrong since it is not enabled (and it would crash Falco too!)

**Which issue(s) this PR fixes**:

Fixes #3229 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(userspace/falco): fixed `falco_metrics::to_text` implementation when running with plugins
```

### CODE REVIEW

**Review by incertum — APPROVED** [review]
Right yes we knew that it was not working for plugin only since the scap regression.
Thanks @FedeDP for adding the safety checks.

**Review by incertum — DISMISSED** [review]
/approve

**Comment by incertum** [comment]
@FedeDP do we also check for null in the output rule code? If not maybe we should add some checks in there too given we have the scap regression?

**Comment by incertum** [comment]
yes @FedeDP please also adjust below code 🙏 since we will continue having the scap regression for a while.

```
void stats_writer::collector::get_metrics_output_fields_wrapper(
		nlohmann::json& output_fields,
		const std::shared_ptr<sinsp>& inspector,
		const std::string& src, uint64_t num_evts,
		uint64_t now, double stats_snapshot_time_delta_sec)
{
	static const char* all_driver_engines[] = {
		BPF_ENGINE, KMOD_ENGINE, MODERN_BPF_ENGINE,
		SOURCE_PLUGIN_ENGINE, NODRIVER_ENGINE, GVISOR_ENGINE };
	const scap_agent_info* agent_info = inspector->get_agent_info();
	const scap_machine_info* machine_info = inspector->get_machine_info();
```

**Comment by FedeDP** [comment]
> yes @FedeDP please also adjust below code 🙏 since we will continue having the scap regression for a while.

For some reason it was not failing on that locally :/ weird, but yep i add the extra checks!

**Comment by incertum** [comment]
> indeed i can confirm that both agent_info and machine_info are not NULL here.

they are not initialized when running Falco with plugin only, see https://github.com/falcosecurity/falco/issues/2821 :/

**Review by incertum — APPROVED** [review]
/approve

File: userspace/falco/falco_metrics.cpp [hunk 1]
```diff
@@ -53,20 +53,20 @@ std::string falco_metrics::to_text(const falco::app::state& state)
 		BPF_ENGINE, KMOD_ENGINE, MODERN_BPF_ENGINE,
 		SOURCE_PLUGIN_ENGINE, NODRIVER_ENGINE, GVISOR_ENGINE };
 
-	std::vector<sinsp*> inspectors;
+	std::vector<std::shared_ptr<sinsp>> inspectors;
 	std::vector<libs::metrics::libs_metrics_collector> metrics_collectors;
 
-	for (const auto& source_info: state.source_infos)
+	for (const auto& source: state.enabled_sources)
```
Comment (FedeDP) [inline userspace/falco/falco_metrics.cpp:59]: Oh well it turns out the issue was actually here: the old code also used the syscall inspector that was not even inited i guess, and thus had NULL agent and machine infos.
That's why stats_writer was not crashing.

I think leaving the checks is ok anyway, more protection for free :)

Comment (FedeDP) [reply userspace/falco/falco_metrics.cpp:59]: cc @incertum

Comment (incertum) [reply userspace/falco/falco_metrics.cpp:59]: Ahh understood, greta job spotting this and agreed more checks help here and also make it clearer that these 2 structs can be NULL in some circumstances.

**Comment by FedeDP** [comment]
/milestone 0.39.0
(will probably become 0.38.1)

**Review by LucaGuerra — APPROVED** [review]
