### PR TITLE
fix(userspace/falco): properly delete metrics timer upon leaving.

### LINKED ISSUE #2757: Falco metrics sent twice
**Describe the bug**
When set the interval to 15m not one but two metric alerts are output with a 3-5 second difference.

**How to reproduce it**
On Falco version 0.35.1 I have the following config:
```
buffered_outputs: false
file_output:
  enabled: false
  filename: ./events.txt
  keep_alive: false 
grpc:
  bind_address: unix:///run/falco/falco.sock
  enabled: false
  threadiness: 0
grpc_output:
  enabled: false
http_output:
  enabled: true
  url: [falcosidekick url]
  user_agent: falcosecurity/falco
insecure: false
  ca_cert: "/tls/ca.crt"
​
json_include_output_property: true
json_include_tags_property: true
json_output: true
libs_logger:
  enabled: false
  severity: debug
load_plugins: []
log_level: info
log_stderr: true
log_syslog: true
metadata_download:
  chunk_wait_us: 1000
  max_mb: 100
  watch_freq_sec: 1
modern_bpf:
  cpus_for_each_syscall_buffer: 2
output_timeout: 2000
outputs:
  max_burst: 1000
  rate: 1
plugins:
- init_config: ""
  library_path: libjson.so
  name: json
priority: debug
program_output:
  enabled: false
  keep_alive: false
  program: 'jq ''{text: .output}'' | curl -d @- -X POST https://hooks.slack.com/services/XXX'
rules_file:
- /etc/falco/rules.d
stdout_output:
  enabled: true
syscall_buf_size_preset: 4
syscall_event_drops:
  actions:
  - log
  - alert
  max_burst: 1
  rate: 0.03333
  simulate_drops: false
  threshold: 0.1
syscall_event_timeouts:
  max_consecutives: 1000
syslog_output:
  enabled: true
time_format_iso_8601: false
watch_config_files: true
webserver:
  enabled: true
  k8s_healthz_endpoint: /healthz
  listen_port: 8765
  ssl_certificate: /etc/falco/falco.pem
  ssl_enabled: false
  threadiness: 0
metrics:
  enabled: true
  interval: 15m
  output_rule: true
  output_file: /tmp/falco_stats.jsonl
```

**Expected behaviour**

1 metric output per 15 min.

**Screenshots**

**Environment**

- Falco version: 

```
Thu Aug 31 23:07:11 2023: Falco version: 0.35.1 (x86_64)
Thu Aug 31 23:07:11 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
{"default_driver_version":"5.0.1+driver","driver_api_version":"4.0.0","driver_schema_version":"2.0.0","engine_version":"17","falco_version":"0.35.1","libs_version":"0.11.3","plugin_api_version":"3.0.0"}
```

- System info:

```
{
  "machine": "x86_64",
  "nodename": "falco-syscall-xxzd4",
  "release": "5.15.107+",
  "sysname": "Linux",
  "version": "#1 SMP Sat May 20 09:38:40 UTC 2023"
}
```
- Cloud provider or hardware configuration: GCP
- OS: 

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel: 

```
Linux falco-syscall-626dc 5.15.107+ #1 SMP Sat May 20 09:38:40 UTC 2023 x86_64 GNU/Linux
```
- Installation method: kubernetes

**Additional context**

Output of `/tmp/falco_stats.jsonl`:
```
tail -n 50 /tmp/falco_stats.jsonl 
{"output_fields":{"evt.source":"syscall","evt.time":1693500164483152436,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":38700,"falco.evts_rate_sec":5023.180875240247,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":195428715,"falco.num_evts_prev":190934317,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011176537714817972,"scap.evts_rate_sec":5038.807910273105,"scap.n_drops":642,"scap.n_drops_perc":0.00022180916426743088,"scap.n_drops_prev":632,"scap.n_drops_scratch_map":642,"scap.n_evts":196044018,"scap.n_evts_prev":191535638},"sample":85}
{"output_fields":{"evt.source":"syscall","evt.time":1693500169751653092,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":38705,"falco.evts_rate_sec":7195.215958989908,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":195466623,"falco.num_evts_prev":195428715,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":7220.650140125939,"scap.n_drops":642,"scap.n_drops_perc":0.0,"scap.n_drops_prev":642,"scap.n_drops_scratch_map":642,"scap.n_evts":196082060,"scap.n_evts_prev":196044018},"sample":86}
{"output_fields":{"evt.source":"syscall","evt.time":1693501064392630167,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":39600,"falco.evts_rate_sec":5059.178056876061,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":199992771,"falco.num_evts_prev":195466623,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.01117766820014737,"scap.evts_rate_sec":5074.448987171103,"scap.n_drops":652,"scap.n_drops_perc":0.0002202735356766032,"scap.n_drops_prev":642,"scap.n_drops_scratch_map":652,"scap.n_evts":200621870,"scap.n_evts_prev":196082060},"sample":87}
{"output_fields":{"evt.source":"syscall","evt.time":1693501069751652561,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":39605,"falco.evts_rate_sec":5312.909315676206,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":200021243,"falco.num_evts_prev":199992771,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":5390.535414135088,"scap.n_drops":652,"scap.n_drops_perc":0.0,"scap.n_drops_prev":652,"scap.n_drops_scratch_map":652,"scap.n_evts":200650758,"scap.n_evts_prev":200621870},"sample":88}
{"output_fields":{"evt.source":"syscall","evt.time":1693501964422811462,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":40500,"falco.evts_rate_sec":5071.126921731968,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":204558234,"falco.num_evts_prev":200021243,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.03241414424895863,"scap.evts_rate_sec":5086.865665358505,"scap.n_drops":681,"scap.n_drops_perc":0.0006372125072949845,"scap.n_drops_prev":652,"scap.n_drops_scratch_map":681,"scap.n_evts":205201830,"scap.n_evts_prev":200650758},"sample":89}
{"output_fields":{"evt.source":"syscall","evt.time":1693501969872137092,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":40505,"falco.evts_rate_sec":4150.605329122165,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":204580852,"falco.num_evts_prev":204558234,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":4168.956223671295,"scap.n_drops":681,"scap.n_drops_perc":0.0,"scap.n_drops_prev":681,"scap.n_drops_scratch_map":681,"scap.n_evts":205224548,"scap.n_evts_prev":205201830},"sample":90}
{"output_fields":{"evt.source":"syscall","evt.time":1693502864483033261,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":41400,"falco.evts_rate_sec":5045.020152702669,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":209094182,"falco.num_evts_prev":204580852,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011178044044425446,"scap.evts_rate_sec":5060.794608458163,"scap.n_drops":691,"scap.n_drops_perc":0.00022087527570756292,"scap.n_drops_prev":681,"scap.n_drops_scratch_map":691,"scap.n_evts":209751990,"scap.n_evts_prev":205224548},"sample":91}
{"output_fields":{"evt.source":"syscall","evt.time":1693502869962570101,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":41405,"falco.evts_rate_sec":6825.75938297734,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":209131584,"falco.num_evts_prev":209094182,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6898.028264739251,"scap.n_drops":691,"scap.n_drops_perc":0.0,"scap.n_drops_prev":691,"scap.n_drops_scratch_map":691,"scap.n_evts":209789788,"scap.n_evts_prev":209751990},"sample":92}
{"output_fields":{"evt.source":"syscall","evt.time":1693503764452844039,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":42300,"falco.evts_rate_sec":5033.543830698018,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":213634040,"falco.num_evts_prev":209131584,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011179551406383579,"scap.evts_rate_sec":5049.327121373551,"scap.n_drops":701,"scap.n_drops_perc":0.0002214067565371452,"scap.n_drops_prev":691,"scap.n_drops_scratch_map":701,"scap.n_evts":214306362,"scap.n_evts_prev":209789788},"sample":93}
{"output_fields":{"evt.source":"syscall","evt.time":1693503769751640545,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":42305,"falco.evts_rate_sec":7076.32383269334,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":213671536,"falco.num_evts_prev":213634040,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":7078.588497884089,"scap.n_drops":701,"scap.n_drops_perc":0.0,"scap.n_drops_prev":701,"scap.n_drops_scratch_map":701,"scap.n_evts":214343870,"scap.n_evts_prev":214306362},"sample":94}
{"output_fields":{"evt.source":"syscall","evt.time":1693504664483089332,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":43200,"falco.evts_rate_sec":5036.912479280542,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":218178220,"falco.num_evts_prev":213671536,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011176537958464678,"scap.evts_rate_sec":5052.360690046733,"scap.n_drops":711,"scap.n_drops_perc":0.00022121417381151578,"scap.n_drops_prev":701,"scap.n_drops_scratch_map":711,"scap.n_evts":218864376,"scap.n_evts_prev":214343870},"sample":95}
{"output_fields":{"evt.source":"syscall","evt.time":1693504669932499873,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":43205,"falco.evts_rate_sec":6722.194946479075,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":218214852,"falco.num_evts_prev":218178220,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6775.778723623973,"scap.n_drops":711,"scap.n_drops_perc":0.0,"scap.n_drops_prev":711,"scap.n_drops_scratch_map":711,"scap.n_evts":218901300,"scap.n_evts_prev":218864376},"sample":96}
{"output_fields":{"evt.source":"syscall","evt.time":1693505564483071605,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":44100,"falco.evts_rate_sec":5063.3548768855735,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":222744279,"falco.num_evts_prev":218214852,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.032418513739084796,"scap.evts_rate_sec":5078.957125032346,"scap.n_drops":740,"scap.n_drops_perc":0.0006382907542043551,"scap.n_drops_prev":711,"scap.n_drops_scratch_map":740,"scap.n_evts":223444684,"scap.n_evts_prev":218901300},"sample":97}
{"output_fields":{"evt.source":"syscall","evt.time":1693505569781801748,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":44105,"falco.evts_rate_sec":4893.625321579242,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":222770209,"falco.num_evts_prev":222744279,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":4950.997558284221,"scap.n_drops":740,"scap.n_drops_perc":0.0,"scap.n_drops_prev":740,"scap.n_drops_scratch_map":740,"scap.n_evts":223470918,"scap.n_evts_prev":223444684},"sample":98}
{"output_fields":{"evt.source":"syscall","evt.time":1693506464484378987,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":45000,"falco.evts_rate_sec":5071.980471995216,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":227308123,"falco.num_evts_prev":222770209,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011176898619046586,"scap.evts_rate_sec":5087.795783541168,"scap.n_drops":750,"scap.n_drops_perc":0.00021968056688130924,"scap.n_drops_prev":740,"scap.n_drops_scratch_map":750,"scap.n_evts":228022982,"scap.n_evts_prev":223470918},"sample":99}
{"output_fields":{"evt.source":"syscall","evt.time":1693506469902241843,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":45005,"falco.evts_rate_sec":4061.0108791576245,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":227330125,"falco.num_evts_prev":227308123,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":4086.482177281602,"scap.n_drops":750,"scap.n_drops_perc":0.0,"scap.n_drops_prev":750,"scap.n_drops_scratch_map":750,"scap.n_evts":228045122,"scap.n_evts_prev":228022982},"sample":100}
{"output_fields":{"evt.source":"syscall","evt.time":1693507364483041332,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":45900,"falco.evts_rate_sec":5063.055235018705,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":231859437,"falco.num_evts_prev":227330125,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.01117842011108686,"scap.evts_rate_sec":5078.834692847515,"scap.n_drops":760,"scap.n_drops_perc":0.00022009812854963256,"scap.n_drops_prev":750,"scap.n_drops_scratch_map":760,"scap.n_evts":232588550,"scap.n_evts_prev":228045122},"sample":101}
{"output_fields":{"evt.source":"syscall","evt.time":1693507369811913687,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":45905,"falco.evts_rate_sec":3941.546841573765,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":231880441,"falco.num_evts_prev":231859437,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":3974.5744669840196,"scap.n_drops":760,"scap.n_drops_perc":0.0,"scap.n_drops_prev":760,"scap.n_drops_scratch_map":760,"scap.n_evts":232609730,"scap.n_evts_prev":232588550},"sample":102}
{"output_fields":{"evt.source":"syscall","evt.time":1693508264422760218,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":46800,"falco.evts_rate_sec":5028.731785943207,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":236379199,"falco.num_evts_prev":231880441,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.01117804466464568,"scap.evts_rate_sec":5044.034529089107,"scap.n_drops":770,"scap.n_drops_perc":0.0002216092019232133,"scap.n_drops_prev":760,"scap.n_drops_scratch_map":770,"scap.n_evts":237122178,"scap.n_evts_prev":232609730},"sample":103}
{"output_fields":{"evt.source":"syscall","evt.time":1693508270083577906,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":46805,"falco.evts_rate_sec":6482.455719743363,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":236415895,"falco.num_evts_prev":236379199,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6504.360682389106,"scap.n_drops":770,"scap.n_drops_perc":0.0,"scap.n_drops_prev":770,"scap.n_drops_scratch_map":770,"scap.n_evts":237158998,"scap.n_evts_prev":237122178},"sample":104}
{"output_fields":{"evt.source":"syscall","evt.time":1693509164483018862,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":47700,"falco.evts_rate_sec":5031.453279073979,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":240916024,"falco.num_evts_prev":236415895,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.032423991644049625,"scap.evts_rate_sec":5047.366750559143,"scap.n_drops":799,"scap.n_drops_perc":0.0006423942076421873,"scap.n_drops_prev":770,"scap.n_drops_scratch_map":799,"scap.n_evts":241673360,"scap.n_evts_prev":237158998},"sample":105}
{"output_fields":{"evt.source":"syscall","evt.time":1693509169902444441,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":47705,"falco.evts_rate_sec":6853.12483004022,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":240953164,"falco.num_evts_prev":240916024,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6853.12483004022,"scap.n_drops":799,"scap.n_drops_perc":0.0,"scap.n_drops_prev":799,"scap.n_drops_scratch_map":799,"scap.n_evts":241710500,"scap.n_evts_prev":241673360},"sample":106}
{"output_fields":{"evt.source":"syscall","evt.time":1693510064422731782,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":48600,"falco.evts_rate_sec":5045.470811417712,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":245466440,"falco.num_evts_prev":240953164,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011179176304346802,"scap.evts_rate_sec":5061.682852894276,"scap.n_drops":809,"scap.n_drops_perc":0.0002208588848658216,"scap.n_drops_prev":799,"scap.n_drops_scratch_map":809,"scap.n_evts":246238278,"scap.n_evts_prev":241710500},"sample":107}
{"output_fields":{"evt.source":"syscall","evt.time":1693510069811873088,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":48605,"falco.evts_rate_sec":4865.339116420638,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":245492660,"falco.num_evts_prev":245466440,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":4859.030133584699,"scap.n_drops":809,"scap.n_drops_perc":0.0,"scap.n_drops_prev":809,"scap.n_drops_scratch_map":809,"scap.n_evts":246264464,"scap.n_evts_prev":246238278},"sample":108}
{"output_fields":{"evt.source":"syscall","evt.time":1693510964392659362,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":49500,"falco.evts_rate_sec":5073.386405830867,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":250031214,"falco.num_evts_prev":245492660,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011178420276217639,"scap.evts_rate_sec":5089.168099576831,"scap.n_drops":819,"scap.n_drops_perc":0.00021965122899255646,"scap.n_drops_prev":809,"scap.n_drops_scratch_map":819,"scap.n_evts":250817136,"scap.n_evts_prev":246264464},"sample":109}
{"output_fields":{"evt.source":"syscall","evt.time":1693510969933336030,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":49505,"falco.evts_rate_sec":3831.6619561313123,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":250052444,"falco.num_evts_prev":250031214,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":3838.5203242110574,"scap.n_drops":819,"scap.n_drops_perc":0.0,"scap.n_drops_prev":819,"scap.n_drops_scratch_map":819,"scap.n_evts":250838404,"scap.n_evts_prev":250817136},"sample":110}
{"output_fields":{"evt.source":"syscall","evt.time":1693511864483114998,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":50400,"falco.evts_rate_sec":5074.935019532767,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":254592226,"falco.num_evts_prev":250052444,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011178807747889144,"scap.evts_rate_sec":5090.019702707769,"scap.n_drops":829,"scap.n_drops_perc":0.00021962209187407044,"scap.n_drops_prev":819,"scap.n_drops_scratch_map":829,"scap.n_evts":255391680,"scap.n_evts_prev":250838404},"sample":111}
{"output_fields":{"evt.source":"syscall","evt.time":1693511869781804523,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":50405,"falco.evts_rate_sec":4142.156262684593,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":254614174,"falco.num_evts_prev":254592226,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":4201.416198281593,"scap.n_drops":829,"scap.n_drops_perc":0.0,"scap.n_drops_prev":829,"scap.n_drops_scratch_map":829,"scap.n_evts":255413942,"scap.n_evts_prev":255391680},"sample":112}
{"output_fields":{"evt.source":"syscall","evt.time":1693512764395124204,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":51300,"falco.evts_rate_sec":5034.806548158822,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":259118379,"falco.num_evts_prev":254614174,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0324162399128383,"scap.evts_rate_sec":5050.881649751461,"scap.n_drops":858,"scap.n_drops_perc":0.000641793693867949,"scap.n_drops_prev":829,"scap.n_drops_scratch_map":858,"scap.n_evts":259932528,"scap.n_evts_prev":255413942},"sample":113}
{"output_fields":{"evt.source":"syscall","evt.time":1693512769962516952,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":51305,"falco.evts_rate_sec":6429.93976181398,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":259154177,"falco.num_evts_prev":259118379,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6473.76638067209,"scap.n_drops":858,"scap.n_drops_perc":0.0,"scap.n_drops_prev":858,"scap.n_drops_scratch_map":858,"scap.n_evts":259968570,"scap.n_evts_prev":259932528},"sample":114}
{"output_fields":{"evt.source":"syscall","evt.time":1693513664483029291,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":52200,"falco.evts_rate_sec":5024.915513951405,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":263649067,"falco.num_evts_prev":259154177,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011179173492457891,"scap.evts_rate_sec":5040.535055155067,"scap.n_drops":868,"scap.n_drops_perc":0.00022178545273729823,"scap.n_drops_prev":858,"scap.n_drops_scratch_map":868,"scap.n_evts":264477432,"scap.n_evts_prev":259968570},"sample":115}
{"output_fields":{"evt.source":"syscall","evt.time":1693513669751672082,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":52205,"falco.evts_rate_sec":6856.7943269395955,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":263685193,"falco.num_evts_prev":263649067,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6876.154151480033,"scap.n_drops":868,"scap.n_drops_perc":0.0,"scap.n_drops_prev":868,"scap.n_drops_scratch_map":868,"scap.n_evts":264513660,"scap.n_evts_prev":264477432},"sample":116}
{"output_fields":{"evt.source":"syscall","evt.time":1693514564482929984,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":53100,"falco.evts_rate_sec":5041.1472273544205,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":268195665,"falco.num_evts_prev":263685193,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011176540342905177,"scap.evts_rate_sec":5056.997796868728,"scap.n_drops":878,"scap.n_drops_perc":0.0002210113745714037,"scap.n_drops_prev":868,"scap.n_drops_scratch_map":878,"scap.n_evts":269038314,"scap.n_evts_prev":264513660},"sample":117}
{"output_fields":{"evt.source":"syscall","evt.time":1693514569781757922,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":53105,"falco.evts_rate_sec":4482.123269125105,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":268219415,"falco.num_evts_prev":268195665,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":4505.147228654927,"scap.n_drops":878,"scap.n_drops_perc":0.0,"scap.n_drops_prev":878,"scap.n_drops_scratch_map":878,"scap.n_evts":269062186,"scap.n_evts_prev":269038314},"sample":118}
{"output_fields":{"evt.source":"syscall","evt.time":1693515464483134647,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":54000,"falco.evts_rate_sec":5073.961120544178,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":272759095,"falco.num_evts_prev":268219415,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011176913616255283,"scap.evts_rate_sec":5089.163958445009,"scap.n_drops":888,"scap.n_drops_perc":0.00021962180247127238,"scap.n_drops_prev":878,"scap.n_drops_scratch_map":888,"scap.n_evts":273615468,"scap.n_evts_prev":269062186},"sample":119}
{"output_fields":{"evt.source":"syscall","evt.time":1693515469781785007,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":54005,"falco.evts_rate_sec":3819.4631887354803,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":272779333,"falco.num_evts_prev":272759095,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":3868.532287908878,"scap.n_drops":888,"scap.n_drops_perc":0.0,"scap.n_drops_prev":888,"scap.n_drops_scratch_map":888,"scap.n_evts":273635966,"scap.n_evts_prev":273615468},"sample":120}
{"output_fields":{"evt.source":"syscall","evt.time":1693516364452876026,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":54900,"falco.evts_rate_sec":5053.572251731539,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":277300618,"falco.num_evts_prev":272779333,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.03241414670833947,"scap.evts_rate_sec":5070.603091503779,"scap.n_drops":917,"scap.n_drops_perc":0.0006392562407941591,"scap.n_drops_prev":888,"scap.n_drops_scratch_map":917,"scap.n_evts":278172488,"scap.n_evts_prev":273635966},"sample":121}
{"output_fields":{"evt.source":"syscall","evt.time":1693516369902312446,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":54905,"falco.evts_rate_sec":6670.414552703415,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":277336968,"falco.num_evts_prev":277300618,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6531.684610424357,"scap.n_drops":917,"scap.n_drops_perc":0.0,"scap.n_drops_prev":917,"scap.n_drops_scratch_map":917,"scap.n_evts":278208082,"scap.n_evts_prev":278172488},"sample":122}
{"output_fields":{"evt.source":"syscall","evt.time":1693517264483093438,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":55800,"falco.evts_rate_sec":5024.36459121761,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":281831668,"falco.num_evts_prev":277336968,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011178420342219969,"scap.evts_rate_sec":5040.092628639113,"scap.n_drops":927,"scap.n_drops_perc":0.00022178997819804515,"scap.n_drops_prev":917,"scap.n_drops_scratch_map":927,"scap.n_evts":282716852,"scap.n_evts_prev":278208082},"sample":123}
{"output_fields":{"evt.source":"syscall","evt.time":1693517269872201429,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":55805,"falco.evts_rate_sec":6407.739473335782,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":281866200,"falco.num_evts_prev":281831668,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6460.438361625698,"scap.n_drops":927,"scap.n_drops_perc":0.0,"scap.n_drops_prev":927,"scap.n_drops_scratch_map":927,"scap.n_evts":282751668,"scap.n_evts_prev":282716852},"sample":124}
{"output_fields":{"evt.source":"syscall","evt.time":1693518164422778542,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":56700,"falco.evts_rate_sec":5026.378737031455,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":286362550,"falco.num_evts_prev":281866200,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011178797773819775,"scap.evts_rate_sec":5042.19673588141,"scap.n_drops":937,"scap.n_drops_perc":0.00022170491076377343,"scap.n_drops_prev":927,"scap.n_drops_scratch_map":937,"scap.n_evts":287262168,"scap.n_evts_prev":282751668},"sample":125}
{"output_fields":{"evt.source":"syscall","evt.time":1693518169811910332,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":56705,"falco.evts_rate_sec":6550.962451040745,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":286397854,"falco.num_evts_prev":286362550,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6580.651834458106,"scap.n_drops":937,"scap.n_drops_perc":0.0,"scap.n_drops_prev":937,"scap.n_drops_scratch_map":937,"scap.n_evts":287297632,"scap.n_evts_prev":287262168},"sample":126}
{"output_fields":{"evt.source":"syscall","evt.time":1693519064422743683,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":57600,"falco.evts_rate_sec":5052.176691254851,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":290917586,"falco.num_evts_prev":286397854,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011178044829328047,"scap.evts_rate_sec":5067.452607318611,"scap.n_drops":947,"scap.n_drops_perc":0.00022058508871270513,"scap.n_drops_prev":937,"scap.n_drops_scratch_map":947,"scap.n_evts":291831030,"scap.n_evts_prev":287297632},"sample":127}
{"output_fields":{"evt.source":"syscall","evt.time":1693519069872184388,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":57605,"falco.evts_rate_sec":4970.785345943131,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":290944674,"falco.num_evts_prev":290917586,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":4989.869873260691,"scap.n_drops":947,"scap.n_drops_perc":0.0,"scap.n_drops_prev":947,"scap.n_drops_scratch_map":947,"scap.n_evts":291858222,"scap.n_evts_prev":291831030},"sample":128}
{"output_fields":{"evt.source":"syscall","evt.time":1693519964483362342,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.0,"falco.duration_sec":58500,"falco.evts_rate_sec":5075.1780347567465,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":295484985,"falco.num_evts_prev":290944674,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.03241631751832543,"scap.evts_rate_sec":5090.987137469218,"scap.n_drops":976,"scap.n_drops_perc":0.0006367393325303099,"scap.n_drops_prev":947,"scap.n_drops_scratch_map":976,"scap.n_evts":296412676,"scap.n_evts_prev":291858222},"sample":129}
{"output_fields":{"evt.source":"syscall","evt.time":1693519969811896391,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.0,"falco.duration_sec":58505,"falco.evts_rate_sec":3936.9176976427348,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":295505963,"falco.num_evts_prev":295484985,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":3991.717009670177,"scap.n_drops":976,"scap.n_drops_perc":0.0,"scap.n_drops_prev":976,"scap.n_drops_scratch_map":976,"scap.n_evts":296433946,"scap.n_evts_prev":296412676},"sample":130}
{"output_fields":{"evt.source":"syscall","evt.time":1693520864483143962,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":59400,"falco.evts_rate_sec":5036.17615099722,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":300011685,"falco.num_evts_prev":295505963,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.011177290012560074,"scap.evts_rate_sec":5052.3541605614,"scap.n_drops":986,"scap.n_drops_perc":0.00022122934492221135,"scap.n_drops_prev":976,"scap.n_drops_scratch_map":986,"scap.n_evts":300954142,"scap.n_evts_prev":296433946},"sample":131}
{"output_fields":{"evt.source":"syscall","evt.time":1693520870023036210,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":59405,"falco.evts_rate_sec":6717.820191076034,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":300048901,"falco.num_evts_prev":300011685,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6706.989655514325,"scap.n_drops":986,"scap.n_drops_perc":0.0,"scap.n_drops_prev":986,"scap.n_drops_scratch_map":986,"scap.n_evts":300991298,"scap.n_evts_prev":300954142},"sample":132}
{"output_fields":{"evt.source":"syscall","evt.time":1693521764483045906,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":60300,"falco.evts_rate_sec":5032.030444300955,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":304549851,"falco.num_evts_prev":300048901,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.01117992966884981,"scap.evts_rate_sec":5047.55489463912,"scap.n_drops":996,"scap.n_drops_perc":0.00022149198774883518,"scap.n_drops_prev":986,"scap.n_drops_scratch_map":996,"scap.n_evts":305506134,"scap.n_evts_prev":300991298},"sample":133}
{"output_fields":{"evt.source":"syscall","evt.time":1693521769811890685,"falco.container_memory_used":44,"falco.cpu_usage_perc":2.1,"falco.duration_sec":60305,"falco.evts_rate_sec":6766.194455895973,"falco.host_boot_ts":1690911899000000000,"falco.host_num_cpus":2,"falco.hostname":"falco-syscall-626dc","falco.kernel_release":"5.15.107+","falco.memory_pss":70,"falco.memory_rss":69,"falco.memory_vsz":1043,"falco.num_evts":304585907,"falco.num_evts_prev":304549851,"falco.start_ts":1693461464391447793,"falco.version":"0.35.1","scap.engine_name":"bpf","scap.evts_drop_rate_sec":0.0,"scap.evts_rate_sec":6821.74120425811,"scap.n_drops":996,"scap.n_drops_perc":0.0,"scap.n_drops_prev":996,"scap.n_drops_scratch_map":996,"scap.n_evts":305542486,"scap.n_evts_prev":305506134},"sample":134}
```

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area engine

**What this PR does / why we need it**:

Properly deletes metrics related timer upon leaving.

**Which issue(s) this PR fixes**:

Fixes #2757 

**Special notes for your reviewer**:

How i tested the fix:
* set metrics enabled and interval 15s
* start Falco
* immediately (before 15s elapses) change interval to eg: 2m
* wait 
* you will receive just one stats after 2min (otherwise you would've received one after 15s since Falco started)

Did the same also playing a bit with the interval values, like restarting Falco 4-5 times in a row updating `metrics.interval` config value.
Everything was sane.

**Does this PR introduce a user-facing change?**:

```release-note
fix(userspace/falco): cleanup metrics timer upon leaving.
```

### CODE REVIEW

File: userspace/falco/app/restart_handler.cpp [hunk 1]
```diff
@@ -31,8 +31,9 @@ limitations under the License.
 
 falco::app::restart_handler::~restart_handler()
 {
-    close(m_inotify_fd);
     stop();
+    close(m_inotify_fd);
```
Comment (FedeDP) [inline userspace/falco/app/restart_handler.cpp:35]: Close inotify_fd after having stopped the secondary thread (so that nobody is using it).
Also, reset it to -1.
/cc @jasondellaluce

**Review by jasondellaluce — APPROVED** [review]
/approve

Lovely, thanks Fede!
